---
apiVersion: v1
kind: Secret
metadata:
  name: orderss49-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/orderss49-app-backend-gitops
